name: Deploy to EC2

on:
  push:
    branches:
#      - main
# 푸쉬용 e e e

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ✅ 코드 받아오기
        uses: actions/checkout@v3

      - name: 🛠️ JAR 빌드 (Gradle)
        run: ./gradlew clean build -x test

      - name: 🔧 Docker Buildx 설정 !
        uses: docker/setup-buildx-action@v2

      - name: 🔑 DockerHub 로그인
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 🐳 Docker 이미지 빌드 & 푸시
        run: |
          docker build -t leesejoon/fantasyshop-backend:latest .
          docker push leesejoon/fantasyshop-backend:latest

      - name: 🚀 EC2에 SSH 접속 후 배포
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull leesejoon/fantasyshop-backend:latest

             # Redis 상태 확인 및 실행 (docker run 유지)
            redis_status=$(docker inspect -f '{{.State.Status}}' redis 2>/dev/null || echo "notfound")
  
            if [ "$redis_status" != "running" ]; then
              echo "🔄 Redis가 실행 중이 아님($redis_status). 재시작합니다."
              docker rm redis || true
              docker run -d --restart=always --name redis -p 6379:6379 redis:latest
            else
              echo "✅ Redis가 이미 실행 중입니다. 유지합니다."
            fi
            
            # 기존 백엔드 컨테이너 중지 및 삭제
            docker-compose -f /home/ec2-user/docker-compose.yml down

            # 새 백엔드 컨테이너 재시작 (env_file 자동 적용)
            docker-compose --env-file /home/ec2-user/.env -f /home/ec2-user/docker-compose.yml up -d --build app
